name: "bbaggins_dbt_quickstart"
version: "1.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  bbaggins_dbt_quickstart:
    +database: ANALYTICS
    +schema: DBT_KLAING   # default schema for your older models

    staging:
      +materialized: view

    marts:
      +materialized: table

    # --- NEW Mortgage Calculator ---
    mortgage:
      +schema: DBT_KLAING_MTG   # new drawer for mortgage models
      staging:
        +materialized: view
      marts:
        +materialized: view
seeds:
  bbaggins_dbt_quickstart:
    +database: RAW
    +schema: SEEDS


